### ISSUE TITLE
Stream from ATV to Airport Express

### ISSUE THREAD

**Issue by JanLp** [apexad/homebridge-airport-express-playing#11]
I have a problem sending audio from my apple tv to my airport. When I send audio from my iphone 12 pro to my airport and pause the sound, it takes 5-10 min and "Homebridge Airport Express Playing" registers no sound and goes off mode. When I do it on my apple tv nothing happens and "Homebridge Airport Express Playing" is in on mode even when my apple tv is on standby. Only way I can get it in off mode is by selecting another audio source before I put my apple tv on standby.
Why is it like that?

**Comment by apexad** [comment]
This is just using the mDNS record flags. It is likely the flags are not updating in the scenario the plugin does not work.
