### ISSUE TITLE
mDNS Errors

### ISSUE THREAD

**Issue by ultrathew** [apexad/homebridge-airport-express-playing#12]
I've been able to get this plugin working at a different location with a similar mix of Airport Expresses and AirPlay 2 speakers, but it just keeps throwing this error over and over:

[23/02/2021, 17:00:44] [Airport Express Playing Platform] Error in mDNS check, found invalid record

What could be the cause?

**Comment by apexad** [comment]
I apologize for not responding to this earlier.
I have just published v2.0.0 and this should fix the likely cause of his issue.

For the technical context as to why, if you are interested:

Prior to version 2.0.0 I was attempting to pull serialNumber from the mDNS record even if it was invalid and I was also only closing the mDNS Browser request when I successfully found the Airport Express device found previously. 

This is changed in 2.0,0 as I am doing a check that I got an mDNS record in the format I expect before attempting to pull serial number from it.
Secondly, in 2.0.0 the mDNS Browser check automatically closes regardless of if I found the record I expected to find or not (this will not cause any issue other than the accessories not updating, but still can on a subsequent check).
