### ISSUE TITLE
"Not supported"

### ISSUE THREAD

**Issue by Metatropics** [apexad/homebridge-airport-express-playing#15]
If installing with "showSwitch": false, the speakers show "Not Supported" under the name/status. I'm trying with a A1392 FW 7.8.1 (Airplay 2). Any suggestions?

**Comment by jsiegenthaler** [comment]
This is because Apple Home App does not support this accessory type. It has to be changed by Apple.

**Comment by alejandrohernandezrosales** [comment]
So are you saying they stopped supporting the entire smart speaker service & categories? 

As far as I've [looked into it](https://github.com/homebridge/homebridge/issues/2553) it seems to be a matter of a missing valid accessory.category and exposing as external.

**Comment by jsiegenthaler** [comment]
There are a number of services that are supposed to be part of an accessory, and the Smart Speaker Service is one of them. Send feedback to Apple if you want it any other way.

**Comment by apexad** [comment]
*This package is deprecated, please use https://github.com/maxileith/homebridge-airport-express-connected (https://www.npmjs.com/package/homebridge-airport-express-connected) instead
