### ISSUE TITLE
Doesn't support new Home Architecture in iOS 16.2/MacOS 13.1

### ISSUE THREAD

**Issue by GoanSausage** [apexad/homebridge-airport-express-playing#16]
Homebridge server cannot be added to Home app with this plugin enabled. It fails with the error...

[Accessory is out of compliance.]

If the plugin is disabled and the server successfully added, once this plugin is enabled, all other HomeBridge accessories go NO RESPONSE in the Home app

**Comment by ctaylora1231** [comment]
I am also unable to use the plug-in after updating to new architecture. Even tried a fresh homebridge install and still unable to get plug-in to work, and it’s also causing other plug-ins to show no response.

**Comment by sloth8871** [comment]
I do not know why this behavior is happening but I think I worked around the issue. I ran into the same issues reported in the most recent few Issues posted here. After some digging I found in my Homebridge logs what looks like 2 identical accessories being created when this plugin loads:
[1/17/2023, 12:05:55 PM] [Airport Express Playing Platform] Searching for Airport Express devices
[1/17/2023, 12:05:55 PM] Homebridge v1.6.0 (HAP v0.11.0) (Homebridge D864) is running on port 51110.
[1/17/2023, 12:05:55 PM] [Airport Express Playing Platform] Restoring existing accessory from cache: Soundbar
[1/17/2023, 12:05:55 PM] [Airport Express Playing Platform] Airport Express device Soundbar (serial number: ********DV2R created!
[1/17/2023, 12:05:55 PM] [Airport Express Playing Platform] Restoring existing accessory from cache: Soundbar
[1/17/2023, 12:05:55 PM] [Airport Express Playing Platform] Airport Express device Soundbar (serial number: ********DV2R created!

Once I noticed this I did the following:
Disable the plugin
go into homebridge cached accessories and delete all airport express accessories
reload homebridge
enable the plugin
go into cached accessories and delete the first duplica accessory ( i did not try deleting the second to see if the behaviour is different so YMMV)
reload homebridge

I can now see my Airport Express as a switch again and it works with automation and toggles properly when airplay2 is sent and stopped.

**Comment by brettcp** [comment]
Same issue here.. for every Airport Express I add (I have 5 now, will be adding 3 more soon), I have to do what @sloth8871 mentioned above (stop, delete the cached duplicate entry, then restart).

Other than that, this plugin is great!  Allows me to toggle the zone power on/off on my Russound MCA-88 when Airplay starts/stops.

**Comment by pierroferrero** [comment]
Hi!
Is the plug-in still working? 
i installed but nothing happened.
I tried the steps mentioned above but it did not fix the problem!
Here is my config! Is it compatible with this plugin? Thanks a lot 
![Uploading 07326D5A-B02B-4F18-9587-B26EDB51C5A6.jpeg…]()

**Comment by sloth8871** [comment]
@pierroferrero it still works with a couple small issues. see the previous posts from above as well as this reddit thread where I posted some more info on how to troubleshoot and get working.
https://old.reddit.com/r/homebridge/comments/10yz51q/airplay_trigger_device_on_play/

**Comment by apexad** [comment]
Updated README to reflect this:
*This package is deprecated, please use https://github.com/maxileith/homebridge-airport-express-connected (https://www.npmjs.com/package/homebridge-airport-express-connected) instead
