### ISSUE TITLE
Toggle Play/Pause

### ISSUE THREAD

**Issue by yonigold1** [apexad/homebridge-airport-express-playing#3]
Hey great plug-in here! very happy with it! but would it be possible to toggle play or pause simply by tapping the icon of the speaker in the home app?

**Comment by jsiegenthaler** [comment]
The plugin is used to only display the device airplaying state, it is not a controller. Use the native controls or the native AirPort Express icon in Homekit to control the playback

**Comment by apexad** [comment]
What @jsiegenthaler mentioned is correct,  This is meant only as a display of the status as well as adding the with allows for automations to be used.

It works by reading the mDNS (Bonjour) record sent by the Airport Express.  Unfortunately adding controls like play/pause is not possible with the way this plugin is implemented and not within the scope of what is currently implemented in homebridge either in regards to airplay2.
