### ISSUE TITLE
FYI: mDNS TXT flags do not change when AirPlaying from iTunes on Win10

### ISSUE THREAD

**Issue by jsiegenthaler** [apexad/homebridge-airport-express-playing#4]
FYI for you

On Win10 there is a great tool called Bonjour Browser that shows all the mDNS data without having to do any command line commands.

I noticed that when iTunes running on Win10 AirPlays to an AirPort Express, the flags do not change on the AirPort Express.

So I took a moment to document my 2 x airplay sources 8iOS devices and iTunes on Win10) and my 3 x AirPlay receivers (AirPort Express, AppleTV, SONOS Speakers)

Here's a summary of the flags on all my devices:

AirPort Express with firmware v7.8.1
Model Airport10.115
Not AirPlaying: 0x4  (b 0000 0000 0100)
AirPlaying from iOS device on iOS 14.3: 0x804  (b 1000 0000 0100)
AirPlaying from iTunes v12.11.0.26 running on Win10: 0x4  (b 0000 0000 0100)

AppleTV with OS v14.3
Model AppleTV6.2
Not AirPlaying: 0x644  (b 0110 0100 0100)
AirPlaying from iOS device on iOS 14.3: AirPlaying: 0x20e44  (b 0010 0000 1110 0100 0100)
AirPlaying from iTunes v12.11.0.26 running on Win10: AirPlaying: 0x20644  (b 0010 0000 0110 0100 0100)

SONOS Symfonisk Speaker or One SL Speaker with firmware 12.2.2:
Not AirPlaying: 0x404  (b 0100 0000 0100)
Playing via SONOS system: 0x404  (b 0100 0000 0100)
AirPlaying from iOS device on iOS 14.3: 0xc04 (b 1100 0000 0100)
AirPlaying from iTunes v12.11.0.26 running on Win10: AirPlaying: 0x404  (1100 0000 0100)

**Comment by apexad** [comment]
I added a note regarding iTunes on Windows 10.  I don't have any plans to add additional devices other than Airport Express (like SONOS Speakers), but I would consider Pull Requests.

**Comment by apexad** [comment]
@jsiegenthaler Actually, do me a favor as I don't have any computers running Windows 10.  Is the `pid` and `gid` records in mDNS different?  I've been contemplating changing to that instead of checking the flags.

pid = gid would mean Not Connected/Show Stopped
pid != gid would mean Connected/Show Playing

**Comment by jsiegenthaler** [comment]
Good question, let me check after dinner tonight

**Comment by jsiegenthaler** [comment]
Win10 not AirPlaying: 
Key: gid  Value: 4a9d5181-5286-4c37-a461-6e57cacde3c8
Key: pi    Value: 4a9d5181-5286-4c37-a461-6e57cacde3c8

Win10 Airplaying
Key: gid
Value: 4a9d5181-5286-4c37-a461-6e57cacde3c8


Win10 AirPlaying:
Key: gid  Value: 4a9d5181-5286-4c37-a461-6e57cacde3c8
Key: pi    Value: 4a9d5181-5286-4c37-a461-6e57cacde3c8

**Comment by apexad** [comment]
So even that does not change? Wow. I'm surprised

**Comment by jsiegenthaler** [comment]
@apexad Remember that the flags show, strictly speaking, the current capabilities, and not whether it is playing or not. The fact that the speaker is playing can be deduced from the capabilities for some (but not all) AirPlay streaming devices.

Obviously, iTunes does not have the same capabilities as some iDevices. Shame. I'll now have to add more scripting ;)

**Comment by apexad** [comment]
So, is there anything in the mDNS record that is different when AirPlaying from Windows 10?

**Comment by jsiegenthaler** [comment]
Looks like we are out of luck:

Airplaying from iPad

;; QUESTION SECTION:
;Stereo._airplay._tcp.local.    IN      TXT

;; ANSWER SECTION:
Stereo._airplay._tcp.local. 10  IN      TXT     "acl=0" "deviceid=00:F7:6F:D6:CE:09" "features=0x445D0A00,0x1C340" "rsf=0x0" "fv=p20.78100.3" "flags=0x804" "model=AirPort10,115" "manufacturer=Apple Inc." "serialNumber=C86NQK6CDV2R" "protovers=1.1" "srcvers=366.0" "pi=4a9d5181-5286-4c37-a461-6e57cacde3c8" "gid=6D7A52EC-0E28-4180-BAF7-7A138843B21A" "gcgl=0" "isGroupLeader=0" "pk=5616d7fceaf08fa1f4971542d5f9e35455122fc10b03da7ae09630d914ee5d0d"

;; Query time: 1 msec
;; SERVER: 192.168.0.180#5353(224.0.0.251)
;; WHEN: Sat Jan 02 16:09:10 CET 2021
;; MSG SIZE  rcvd: 422



Airplaying from iTunes

;; QUESTION SECTION:
;Stereo._airplay._tcp.local.    IN      TXT

;; ANSWER SECTION:
Stereo._airplay._tcp.local. 10  IN      TXT     "acl=0" "deviceid=00:F7:6F:D6:CE:09" "features=0x445D0A00,0x1C340" "rsf=0x0" "fv=p20.78100.3" "flags=0x4" "model=AirPort10,115" "manufacturer=Apple Inc." "serialNumber=C86NQK6CDV2R" "protovers=1.1" "srcvers=366.0" "pi=4a9d5181-5286-4c37-a461-6e57cacde3c8" "gid=4a9d5181-5286-4c37-a461-6e57cacde3c8" "gcgl=0" "pk=5616d7fceaf08fa1f4971542d5f9e35455122fc10b03da7ae09630d914ee5d0d"

;; Query time: 2 msec
;; SERVER: 192.168.0.180#5353(224.0.0.251)
;; WHEN: Sat Jan 02 16:10:03 CET 2021
;; MSG SIZE  rcvd: 404


Not AirPlaying from anything (no iPad, no iTunes)

;; QUESTION SECTION:
;Stereo._airplay._tcp.local.    IN      TXT

;; ANSWER SECTION:
Stereo._airplay._tcp.local. 10  IN      TXT     "acl=0" "deviceid=00:F7:6F:D6:CE:09" "features=0x445D0A00,0x1C340" "rsf=0x0" "fv=p20.78100.3" "flags=0x4" "model=AirPort10,115" "manufacturer=Apple Inc." "serialNumber=C86NQK6CDV2R" "protovers=1.1" "srcvers=366.0" "pi=4a9d5181-5286-4c37-a461-6e57cacde3c8" "gid=4a9d5181-5286-4c37-a461-6e57cacde3c8" "gcgl=0" "pk=5616d7fceaf08fa1f4971542d5f9e35455122fc10b03da7ae09630d914ee5d0d"

**Comment by apexad** [comment]
Well, unfortunately being able to check if an airport express is getting music from Windows 10 looks like it is not possible.
