### ISSUE TITLE
Switch name

### ISSUE THREAD

**Issue by adamrzanek** [apexad/homebridge-airport-express-playing#5]
Switch and speaker name always is back to “switch” after homebridge restart

**Comment by apexad** [comment]
Is this happening in Homebridg or Home app? Screenshots maybe?

**Comment by adamrzanek** [comment]
Sorry, here’s the video
https://streamable.com/vncdhq

**Comment by apexad** [comment]
I wonder If this is possibly a Homebridge 1.2.x issue (as that release was actually pulled).  I will put this on hold until 1.3.x is out so we can see if it is still happening.

**Comment by adamrzanek** [comment]
It was happening on 1.1.7 too

**Comment by apexad** [comment]
This could also be related to this plugin being 'static' vs dynamic (see #8).  I'm planning to switch it over in the coming days so hopefully doing that will resolve this issue.

**Comment by adamrzanek** [comment]
@apexad thanks man, otherwise great plugin. Helped me a lot with automate my iPod Hi-fi/airport express setup! :)

**Comment by apexad** [comment]
tis is related to #8
I hope to fix it soon.
