### ISSUE TITLE
Devices do not persist after airport express restart

### ISSUE THREAD

**Issue by machineglow** [apexad/homebridge-airport-express-playing#8]
Hi,  

I've had this plug-in loaded for a week or so now and love it. However I've noticed a strange behaviour. Every now and then I'll see the airport express switch and speaker show up in my favourites and in my default room. I reassign it back to its designated room but eventually it'll get reset back to defaults and favourites.  

This also kills/deletes any automation I've created for the devices. 

I think this is triggered when I've restarted the airport express or it's been turned off for a few minutes but I can't reproduce it. 

I have two airport expresses and this has happened for both but weirdly not at the same time. 

Any ideas?

Thanks!

**Comment by apexad** [comment]
You're right, the accessories are not cached.  I'll work on this at some point

**Comment by machineglow** [comment]
gotcha. I'll keep an eye out for updates in the future and hold off on automations.  

Thanks!!!

**Comment by apexad** [comment]
Should still be safe to do automations, even if they occasionally break.  I'll work on making sure devices get cached though (converting this to dynamic vs static).

**Comment by mayurankv** [comment]
Hi, just wanted to thank you so much for the amazing plugin, really improved my speaker setup! I'm also having this issue with the devices disappearing and reappearing as default devices (subsequently killing automations). I wanted to add that my airports don't restart nor my homebridge instance (to the best of my knowledge) when this happens and sometimes it happens to just one of the two airports I'm using. Not sure if that helps but hopefully it does. Were you able to make the change to cacheing?

(This also brings up my hatred of automation control and organisation in HomeKit, apple please pull your thumb out :(   )

**Comment by apexad** [comment]
Have not had a chance to add cache yet. Will try to get to it soon as I am beginning to have a little time again to work on homebridge plugins.

**Comment by mayurankv** [comment]
Thank you! Very much look forward to this. Again I really appreciate your effort!

**Comment by apexad** [comment]
Should be fixed in 2.0.0 now!

**Comment by machineglow** [comment]
Amazing! Thx!
